### PR TITLE
Enables Brave News at 100% for Nightly Android

### PR DESCRIPTION
**Pull request by alexsafe**
Issue here: brave/brave-browser#19770
Percentages discussion here: https://bravesoftware.slack.com/archives/CU56GUJ1H/p1638207099192300

### CODE REVIEW

**Comment by bsclifton** [comment]
Looks like this is blocked on https://github.com/brave/brave-browser/issues/19794

**Review by kjozwiak — APPROVED** [review]
Uplift into `production` approved after deliberating with @brave/uplift-approvers. Most of the issues have been resolved via https://github.com/brave/brave-core/pull/11335.

However, https://github.com/brave/brave-browser/issues/19794 is still occurring but seems hard to reproduce. @alexsafe spent sometime investigating but couldn't figure it out. Hopefully having this life will generate some new data from users that we can use to narrow down the issue. @srirambv also mentioned this doesn't happen 100% of the time.

**Comment by alexsafe** [comment]
@kjozwiak i think i may have cracked it. will do a PR tomorrow

**Comment by kjozwiak** [comment]
> @kjozwiak i think i may have cracked it. will do a PR tomorrow

Awesome 👍

**Pull request merged**
