### PR TITLE
Enable cosmetic filtering on child frames (`production`)

### PR DESCRIPTION
**Pull request by antonok-edm**
`main` PR: https://github.com/brave/brave-variations/pull/360

### CODE REVIEW

**Comment by kjozwiak** [comment]
Adding the `Uplift/Blocked` as we're going to wait ~a week before merging this into `production` as discussed.

**Comment by iefremov** [comment]
I thought we wanted to add some feature parameters that @atuchin-m introduced at his PR. Also IMO we'd better to gradually roll this out for STABLE users, 100% NIGHTLY and BETA is ok @kjozwiak

**Comment by antonok-edm** [comment]
Updated to 100% for nightly/beta only

**Comment by LaurenWags** [comment]
Adding `Uplift/Blocked` pending discussions from thread under https://bravesoftware.slack.com/archives/C01LKMP6X36/p1668103608663869

**Comment by LaurenWags** [comment]
Closing as per https://bravesoftware.slack.com/archives/C01LKMP6X36/p1668710265484509?thread_ts=1668103608.663869&cid=C01LKMP6X36

**Comment by antonok-edm** [comment]
Closing in favor of #466

**Pull request closed without merging**
