### PR TITLE
Adds a 50/50 rollout of certain client hints in Nightly.

### PR DESCRIPTION
**Pull request by mkarolin**
Rollout for https://github.com/brave/brave-browser/issues/24009 (https://github.com/brave/brave-core/pull/14155)

### CODE REVIEW

**Review by bsclifton — APPROVED** [review]
++

**Comment by kjozwiak** [comment]
## `Nightly` channel

### `AllowCertainClientHintsStudy:Enabled` (set as `50%`)

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.41 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.918)
```

Launched `1.45.41 Chromium: 105.0.5195.102` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed` and ensured the following:


```
* sec-ch-ua: "Brave Browser";v"105", "Not)A;Brand";v="8", "Chromium";v="105"
* sec-ch-ua-mobile: ?0
* sec-ch-platform: "Windows"
```

**`Example`** | **`Example`**
---------------|-----------------
enabledGriffin | requestHeadersGriffinEnabled

### `AllowCertainClientHintsStudy:Disabled` (set as `50%`)

Launched `1.45.41 Chromium: 105.0.5195.102` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed` and ensured the following:

* ensured that `sec-ch-ua`, `sec-ch-ua-mobile` & `sec-ch-platform` weren't present via the `Request Headers`

**`Example`** | **`Example`**
---------------|-----------------
disabledGriffin | requestHeadersGriffinDisabled

**Comment by kjozwiak** [comment]
# `Nightly` channel (Android/Mobile verification)

## `AllowCertainClientHintsStudy:Enabled` (set as `50%`)

Verification **PASSED** on `Samsung S10+` running `Android 13`  using the following build(s):

```
Brave | 1.45.43 Chromium: 105.0.5195.102 (Official Build) canary (32-bit)
--- | ---
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Android 12; Build/SP1A.210812.016
```

Launched `1.45.43 Chromium: 105.0.5195.102` using the instructions outlined via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800 and ensured the following:

```
* sec-ch-ua: "Brave Browser";v="105", "Not)A;Brand";v="8", "Chromium";v="105"
* sec-ch-ua-mobile: ?1
* sec-ch-platform: "Android"
```

**`Example`** | **`Example`**
---------------|-----------------
Screenshot_20220913-002623_Brave - Nightly | requestEnabled

## `AllowCertainClientHintsStudy:Disabled` (set as `50%`)

Verification **PASSED** on `Samsung S10+` running `Android 13`  using the following build(s):

```
Brave | 1.45.43 Chromium: 105.0.5195.102 (Official Build) canary (32-bit)
--- | ---
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Android 12; Build/SP1A.210812.016
```

Launched `1.45.43 Chromium: 105.0.5195.102` using the instructions outlined via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800 and ensured the following:

* ensured that `sec-ch-ua`, `sec-ch-ua-mobile` & `sec-ch-platform` weren't present via the `Request Headers`

**`Example`** | **`Example`**
---------------|-----------------
Screenshot_20220913-002331_Brave - Nightly | requestDisabled

# `BETA` channel (Desktop verification)

Verification **PASSED** on `Samsung S10+` running `Android 13`  using the following build(s):

```
Brave | 1.44.82 Chromium: 105.0.5195.102 (Official Build) beta (32-bit)
--- | ---
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Android 12; Build/SP1A.210812.016
```

Launched `1.44.82 Chromium: 105.0.5195.102` using the instructions outlined via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800 and ensured the following:

* ensured that `AllowCertainClientHintsStudy` wasn't appearing/being displayed under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Enabled` never appeared under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Disabled` never appeared under `brave://version`

Screenshot_20220913-003804_Brave - Beta

# `Release` channel (Desktop verification)

Verification **PASSED** on `Samsung S10+` running `Android 13`  using the following build(s):

```
Brave | 1.43.90 Chromium: 105.0.5195.102 (Official Build) (32-bit)
--- | ---
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Android 12; Build/SP1A.210812.016
```

Launched `1.43.90 Chromium: 105.0.5195.102` using the instructions outlined via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800 and ensured the following:

* ensured that `AllowCertainClientHintsStudy` wasn't appearing/being displayed under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Enabled` never appeared under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Disabled` never appeared under `brave://version`

Screenshot_20220913-004250_Brave

**Comment by kjozwiak** [comment]
# `Nightly` channel (Android/Mobile verification)

## `AllowCertainClientHintsStudy:Enabled` (set as `50%`)

Verification **PASSED** on `Samsung S10+` running `Android 12`  using the following build(s):

```
Brave | 1.46.32 Chromium: 106.0.5249.91 (Official Build) canary (32-bit)
--- | ---
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Android 12; Build/SP1A.210812.016
```

Launched `1.46.32 Chromium: 106.0.5249.91` using the instructions outlined via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800 and ensured the following:

```
sec-ch-ua: "Chromium";v="106", "Brave";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?1
sec-ch-ua-platform: "Android"
```

**`Example`** | **`Example`**
---------------|-----------------
Screenshot_20221004-145357_Brave - Nightly | androidDevToolsEnabled

## `AllowCertainClientHintsStudy:Disabled` (set as `50%`)

Verification **PASSED** on `Samsung S10+` running `Android 12`  using the following build(s):

```
Brave | 1.46.32 Chromium: 106.0.5249.91 (Official Build) canary (32-bit)
--- | ---
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Android 12; Build/SP1A.210812.016
```

Launched `1.46.32 Chromium: 106.0.5249.91` using the instructions outlined via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800 and ensured the following:

* ensured that `sec-ch-ua`, `sec-ch-ua-mobile` & `sec-ch-platform` weren't present via the `Request Headers`

**`Example`** | **`Example`**
---------------|-----------------
Screenshot_20221004-144539_Brave - Nightly | androidDevToolsDisabled

# `BETA` channel (Desktop verification)

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 22H2 (Build 22621.521)
```

Launched `1.45.85 Chromium: 106.0.5249.91` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed` and ensured the following:

* ensured that `AllowCertainClientHintsStudy` wasn't appearing/being displayed under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Enabled` never appeared under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Disabled` never appeared under `brave://version`

image

# `Release` channel (Desktop verification)

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 22H2 (Build 22621.521)
```

Launched `1.44.105 Chromium: 106.0.5249.91` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed` and ensured the following:

* ensured that `AllowCertainClientHintsStudy` wasn't appearing/being displayed under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Enabled` never appeared under `brave://version`
  * ensured that `AllowCertainClientHintsStudy:Disabled` never appeared under `brave://version`

image

**Pull request merged**
