### PR TITLE
predictor experiments

### PR DESCRIPTION
**Pull request by iambrianfung**
uplift of https://github.com/brave/brave-variations/pull/712

### CODE REVIEW

**Review by tmancey — APPROVED** [review]

**Comment by iambrianfung** [comment]
blocked awaiting review approval and work for https://github.com/brave/reviews/issues/1507

**Comment by kjozwiak** [comment]
@tmancey @iambrianfung if the above even valid anymore? Looks like https://github.com/brave/reviews/issues/1507 has been reviewed? If this isn't valid anymore, can we close it off? It's been on my `uplift list` for a while 😆

**Comment by tmancey** [comment]
Good to close as not required :-), thanks

**Comment by kjozwiak** [comment]
> Good to close as not required :-), thanks

Closing as per the above. Thanks @tmancey.

**Pull request closed without merging**
