### PR TITLE
Enable cosmetic filtering on child frames (`main`)

### PR DESCRIPTION
**Pull request by antonok-edm**
See https://bravesoftware.slack.com/archives/C3T9S9WKD/p1662676935341739?thread_ts=1662544398.836149&cid=C3T9S9WKD

### CODE REVIEW

**Comment by antonok-edm** [comment]
Looks like we're ready to pick this up again @kjozwiak: https://bravesoftware.slack.com/archives/C3T9S9WKD/p1664492345525849?thread_ts=1662544398.836149&cid=C3T9S9WKD

**Comment by antonok-edm** [comment]
Note that I've added `"min_version": "106.1.46.14"`, which is the minimum version since https://github.com/brave/brave-core/pull/15163 was merged into Nightly. That way we don't have to pick out specific channels here.

**Comment by antonok-edm** [comment]
Test plan can be used from https://github.com/brave/brave-core/pull/14020, although @atuchin-m may have other requests for performance testing

**Comment by kjozwiak** [comment]
Going to approve/merge this into `main` (staging) so I can start running through the STR/Cases mentioned via https://github.com/brave/brave-variations/pull/360#issuecomment-1268014711. I'll double check with @atuchin-m if there's anything else that might need to be verified once that's completed. If everyone agrees, we'll get a quick review of https://github.com/brave/brave-variations/pull/361/files and get it merged into `production`.

**Comment by kjozwiak** [comment]
# `Desktop` verification

## `Test Case #1` -  https://dev-pages.bravesoftware.com/filtering/text-ads.html

As per https://github.com/brave/brave-core/pull/14020#issuecomment-1171598768, running through https://dev-pages.bravesoftware.com/filtering/text-ads.html while `BraveAdblockCosmeticFilteringChildFrames` is enabled via `CosmeticFilteringChildFramesStudy`.

### `Win 11 x64`

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.47.61 Chromium: 107.0.5304.110 (Official Build) nightly (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.819)
```

* launched `1.47.61 Chromium: 107.0.5304.110` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed` and ensured `brave://version` wasn't listing any variation studies
* restarted the browser once more using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed`
* ensured that `CosmeticFilteringChildFramesStudy:Enabled` via `brave://version`
* visited https://dev-pages.bravesoftware.com/filtering/text-ads.html and followed the `Frame tests`
  * `Local frame containing a text ad` & `Local frame containing a low-text ad`

**Pull request merged**
