### PR TITLE
Adjust HangWatcher params

### PR DESCRIPTION
**Pull request by atuchin-m**
For https://github.com/brave/brave-browser/issues/21728
PR to main branch: https://github.com/brave/brave-variations/pull/232

### CODE REVIEW

**Comment by kjozwiak** [comment]
@iefremov @atuchin-m is there anything @brave/qa-team can do here in terms of verifying that things are working on staging before merging this into `production`? Originally https://github.com/brave/brave-browser/issues/20304 was labelled as `QA/No` so not maybe not but figured I would ask just in case 👍

**Comment by atuchin-m** [comment]
@kjozwiak 
IMHO we don't need anything to test, expect sanity check that browser works well.
I've tested this myself, all is good:
image

**Comment by kjozwiak** [comment]
@atuchin-m sounds good 👍 Just waiting for @iefremov to review the above. Usually we try to get one review before we merge into `production`. Usually if there's a review on the `main` PR, that's good enough as well but there's no reviews on https://github.com/brave/brave-variations/pull/232.

**Comment by iefremov** [comment]
lgtm @kjozwiak

**Review by kjozwiak — APPROVED** [review]
> lgtm @kjozwiak

awesome, thanks 👍 Uplift into `production` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
