### PR TITLE
Enable native cosmetic filtering backend on Release channel

### PR DESCRIPTION
**Pull request by antonok-edm**
Followup to https://github.com/brave/brave-variations/pull/81, still no reported regressions so far

### CODE REVIEW

**Comment by antonok-edm** [comment]
@iefremov I've also included the updated version here as per https://github.com/brave/brave-variations/pull/81#discussion_r667868753

**Comment by kjozwiak** [comment]
@iefremov mind taking a look? Once you give the ++ we'll approve/merge 👍

**Review by iefremov — APPROVED** [review]
lgtm!

**Review by kjozwiak — APPROVED** [review]

**Comment by kjozwiak** [comment]
Uplift into `Release` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
