### PR TITLE
Remove conversion attribution frequency capping

### PR DESCRIPTION
**Pull request by tmancey**

### CODE REVIEW

**Review by kjozwiak — APPROVED** [review]
Merging into `main` so QA can run through the above on `staging` before uplifting https://github.com/brave/brave-variations/pull/1048 into `production`.

**Comment by kjozwiak** [comment]
@aseren @iambrianfung merged the above into `main` so @btlechowski can run through the above on `staging` before uplifting. However, mind double checking/reviewing the above study? Can leave a review/approval via https://github.com/brave/brave-variations/pull/1048.

**Comment by aseren** [comment]
@kjozwiak, there is an issue with this PR: we have two studies with same names on same platforms, this can lead to a conflict. We are raising the PR to fix it.

**Comment by tmancey** [comment]
@aseren resolved and added PR link to uplift request

**Pull request merged**
