### PR TITLE
Enable PartitionBlinkMemoryCacheStudy on 5% release.

### PR DESCRIPTION
**Pull request by goodov**
Release 5%.

https://github.com/brave/brave-browser/issues/18831

### CODE REVIEW

**Comment by kjozwiak** [comment]
@goodov @pes10k assuming we need to wait till https://github.com/brave/brave-browser/issues/18831 is on the `release` channel via `1.34.x` before we push this live on `production` via `Griffin`?

**Comment by pes10k** [comment]
I don’t think we strictly need to, since if we push the giffin change before the code change makes it to stable, it’ll no op until the code catches up, but no strong preference on my end

**Comment by kjozwiak** [comment]
As per the discussion on Slack with @pes10k & @goodov, we'll wait till `1.34.x` is live and then push this into `production` and enable ` PartitionBlinkMemoryCacheStudy` on `RELEASE` at `5%`.

**Review by kjozwiak — APPROVED** [review]
Uplift into `production` at `5%` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
