### PR TITLE
Dashboard add support for min max os version

### PR DESCRIPTION
**Pull request by tmancey**

### CODE REVIEW

**Comment by iefremov** [comment]
@moritzhaller is this branch alive or we can skip this change?

**Comment by moritzhaller** [comment]
iirc there was another PR fixing this. @tmancey can you confirm and if so close this ticket?

**Comment by kjozwiak** [comment]
hmm not sure if this is different, but https://github.com/brave/brave-variations/pull/130 was merged into `production` to add support for both `min` & `max` OS versions. I have no idea what use the `dashboard` branch for.

* `main` - https://github.com/brave/brave-variations/pull/126 - **`Merged`**
* `production` - https://github.com/brave/brave-variations/pull/130 - **`Merged`**

**Comment by tmancey** [comment]
Closing as fix is not required for dashboard

**Pull request closed without merging**
