### PR TITLE
Enable BraveVPN for Windows/macOS 100% (staging)

### PR DESCRIPTION
**Pull request by bsclifton**
Enable `BraveVPN` feature on Windows and macOS (brave://flags/#brave-vpn)

Enables for STAGING brave-variation servers

Addresses https://github.com/brave/brave-browser/issues/25680

### CODE REVIEW

**Comment by kjozwiak** [comment]
Going to label this as `PR/Blocked` for now as per the discussion we had via the VPN status meeting. We'll get this merged into `staging` once the website has been fixed/is ready including the various issues we're having with connectons. @bsclifton please let @LaurenWags and @stephendonner know when we're good to proceed with the above.

**Review by kjozwiak — APPROVED** [review]
LGTM 👍 Merging so we can verify so we're ready to push out https://github.com/brave/brave-variations/pull/535 once `1.49.x` goes out.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using version: 

```
Brave	1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
Revision	c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS	Android 13; Build/TP1A.220624.014
```

**Variations server url:** `https://variations.bravesoftware.com/seed`
**Experiment:** `CrossPlatformVPNStudy`

- Ensured that `CrossPlatformVPNStudy` is `Enabled` under `brave://version` using **staging** variations server on Android ARM
- Ensured that experiment `BraveVPNLinkSubscriptionAndroidUI` experiment is removed from the active variations per https://github.com/brave/brave-variations/pull/537 in **Staging**
- Ensured that link subscription button is not shown until VPN profile is enabled

Variations/Version | Active Variations | VPN Settings
-|-|-
screenshot-1678393560395 | screenshot-1678393573437 | screenshot-1678393612160

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

## Without staging Griffin (current/previous default):

### Steps:
1. installed `1.49.120`
2. launched Brave using defaults:
`
./Brave\ Browser
`
3. opened `brave://version`
4. confirmed no `CrossPlatformVPNStudy:Enabled` study
5. restarted Brave
6. looked again at `brave://version`

### Confirmed:
* no `CrossPlatformVPNStudy:Enabled` study on `brave://version` (but other studies were pulled in)
* `Enable experimental Brave VPN` is set to `Default`


`brave://version` | `brave://flags`
------------------|--------------
Screen Shot 2023-03-09 at 1 10 28 PM | Screen Shot 2023-03-09 at 1 15 08 PM



## Staging Griffin seed:

###  Steps:
1. installed `1.49.120`
2. launched Brave using the staging Griffin-server/seed:
`
./Brave\ Browser --variations-server-url=https://variations.bravesoftware.com/seed
`
3. opened `brave://version`
4. confirmed no `CrossPlatformVPNStudy:Enabled` study
5. restarted Brave
6. looked again at `brave://version`

### Confirmed:
* `CrossPlatformVPNStudy:Enabled` study is enabled on `brave://version`
* `Enable experimental Brave VPN` is set to `Default`
* the browser `VPN` toolbar button is present, and shows the `Buy/Already purchased...?` card

`brave://version` | `brave://flags` | w/`Buy/Already purchased...` card 
------------------|---------------|---------------------------------
Screen Shot 2023-03-09 at 1 11 08 PM | Screen Shot 2023-03-09 at 1 14 34 PM | Screen Shot 2023-03-09 at 1 37 08 PM

**Comment by stephendonner** [comment]
## Verified `PASSED`  using 

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 22H2 (Build 19045.2673)




## Without staging Griffin (current/previous default):

### Steps:
1. installed `1.49.120`
2. launched Brave using defaults:
`
./Brave\ Browser
`
3. opened `brave://version`
4. confirmed no `CrossPlatformVPNStudy:Enabled` study
5. restarted Brave
6. looked again at `brave://version`

### Confirmed:
* no `CrossPlatformVPNStudy:Enabled` study on `brave://version` (but other studies were pulled in)
* `Enable experimental Brave VPN` is set to `Default`


`brave://version` | `brave://flags`
------------------|--------------
image | image (1)





## Staging Griffin seed:

###  Steps:
1. installed `1.49.120`
2. launched Brave using the staging Griffin-server/seed:
`
./Brave\ Browser --variations-server-url=https://variations.bravesoftware.com/seed
`
3. opened `brave://version`
4. confirmed no `CrossPlatformVPNStudy:Enabled` study
5. restarted Brave
6. looked again at `brave://version`

### Confirmed:
* `CrossPlatformVPNStudy:Enabled` study is enabled on `brave://version`
* `Enable experimental Brave VPN` is set to `Default`
* the browser `VPN` toolbar button is present, and shows the `Buy/Already purchased...?` card

`brave://version` | `brave://flags` | w/`Buy/Already purchased...` card 
------------------|---------------|---------------------------------
image | image (3) | image (2)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

#### Without staging Griffin (current/previous default):
-----

Steps:

1. installed 1.49.120
2. launched Brave using defaults
3. opened `brave://version`
4. confirmed no `CrossPlatformVPNStudy:Enabled` study
5. restarted Brave
6. looked again at `brave://version`

### Confirmed:
- no `CrossPlatformVPNStudy:Enabled` study on `brave://version` (but other studies were pulled in)
- Enable experimental Brave VPN is set to Default

step 3-4 | `brave://version` | `brave://flags`
----- | ------ | ------
image|image|image


#### Staging Griffin seed:
-----

Steps:

1. installed 1.49.120
2. launched Brave using the staging Griffin-server/seed:  `brave.exe  --variations-server-url=https://variations.bravesoftware.com/seed`
3. opened `brave://version`
4. confirmed no `CrossPlatformVPNStudy:Enabled` study
5. restarted Brave
6. looked again at `brave://version`

 Confirmed:

-  `CrossPlatformVPNStudy:Enabled study` is enabled on `brave://version`
-  `Enable experimental Brave VPN` is set to Default
-  the browser `VPN` toolbar button is present, and shows the `Buy/Already purchased...?` card

`step 3-4` | `brave://version` | `brave://flags` | `w/Buy/Already purchased... card`
------- |----- | ----- | -------
image|image|image|image

**Pull request merged**
