### PR TITLE
Fix #101 - Enable Gemini on Nightly and Set to 10% on Beta

### LINKED ISSUE #101: Enable Gemini in Nightly and set to 10% on Beta (staging)

### PR DESCRIPTION
**Pull request by jumde**
fix #101

### CODE REVIEW

**Comment by kjozwiak** [comment]
We'll get this merged into `main` (staging) once a dev takes a look to make sure the code looks good 👍 At that point, we'll quickly check to make sure it's working and merge into `production` on Monday.

**Review by moritzhaller — APPROVED** [review]

**Comment by moritzhaller** [comment]
@kjozwiak LGTM name maps to rewards feature and channels + % looks ok

**Comment by kjozwiak** [comment]
> @kjozwiak LGTM name maps to rewards feature and channels + % looks ok

awesome, thanks @moritzhaller 👍

**Review by kjozwiak — APPROVED** [review]
Uplift into `main (staging)` approved after deliberating with @brave/uplift-approvers.

**Pull request merged**
